{{- if .Values.ingressGateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "sonarqube.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "sonarqube.labels" . | indent 4 }}
spec:
  gateways:
    - {{ .Values.ingressGateway.name | quote }}
  hosts:
    {{- range .Values.ingressGateway.host }}
    - {{ . | quote }}
    {{- end }}
  http:
  - match:
    {{- range .Values.ingressGateway.matchPrefix }}
    - uri:
        prefix: {{ . | quote }}
    {{- end }}
    route:
    - destination:
        host: {{ (print (include "sonarqube.fullname" .) "." .Release.Namespace ".svc.cluster.local") | quote }}
        port:
          number: {{ .Values.ingressGateway.port }}
{{- end }}
