{{ if .Values.dataPersistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metersphere-data-pvc
spec:
  accessModes:
    - {{.Values.dataPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.dataPersistence.size}}
  storageClassName: {{.Values.dataPersistence.storageClass}}
{{if .Values.taskRunner.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-runner-data-pvc
spec:
  accessModes:
    - {{.Values.dataPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.dataPersistence.size}}
  storageClassName: {{.Values.dataPersistence.storageClass}}
{{end}}
{{end}}
