apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: g32-prod-com-cert-test
  namespace: istio-system
spec:
  secretName: g32-prod-com-cert-test
  renewBefore: 240h
  dnsNames:
  - '*.g32-prod.com'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
