{{- if .Values.koko.enabled }}
{{- with .Values.koko }}
{{- $fullName := include "jumpserver.fullname" $ }}
{{- $containerName := "jms-koko" }}
{{- $registryName := $.Values.global.imageRegistry | default .image.registry }}
{{- $imageOwner :=  $.Values.global.imageOwner | default "jumpserver" }}
{{- $imageName := "koko" }}
{{- $imageTag := "v3.10.1" }}
{{- $imageWithTag := printf "%s/%s/%s:%s" $registryName $imageOwner $imageName $imageTag | quote }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-{{ $containerName }}"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.global.imagePullSecrets }}
      {{- end }}
      serviceAccountName: {{ template "jumpserver.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ $imageWithTag }}
          imagePullPolicy: {{ .image.pullPolicy | quote }}
          ports:
            - name: web
              containerPort: {{ .service.web.port }}
              protocol: TCP
            - name: ssh
              containerPort: {{ .service.ssh.port }}
              protocol: TCP
          env:
            - name: CORE_HOST
              value: "http://{{ $fullName }}-jms-core:{{ $.Values.core.service.web.port }}"
            - name: BOOTSTRAP_TOKEN
              value: {{ $.Values.core.config.bootstrapToken | quote }}
            - name: LOG_LEVEL
              value: {{ .config.log.level | quote }}
            - name: SSHD_PORT
              value: {{ .service.ssh.port | quote }}
            - name: HTTPD_PORT
              value: {{ .service.web.port | quote }}
            - name: REUSE_CONNECTION
              value: "false"
            - name: SHARE_ROOM_TYPE
              value: "redis"
            {{- if include "jumpserver.sentinel.hosts" $ }}
            - name: REDIS_SENTINEL_HOSTS
              value: {{ include "jumpserver.sentinel.hosts" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.sentinel.password" $ }}
            - name: REDIS_SENTINEL_PASSWORD
              value: {{ include "jumpserver.sentinel.password" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.sentinel.socketTimeout" $ }}
            - name: REDIS_SENTINEL_SOCKET_TIMEOUT
              value: {{ include "jumpserver.sentinel.socketTimeout" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.host" $ }}
            - name: REDIS_HOST
              value: {{ include "jumpserver.redis.host" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.port" $ }}
            - name: REDIS_PORT
              value: {{ include "jumpserver.redis.port" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.password" $ }}
            - name: REDIS_PASSWORD
              value: {{ include "jumpserver.redis.password" $ | quote }}
            {{- end }}
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/koko/data"
              name: "jms-koko-data"
              {{- if .persistence.subPath }}
              subPath: {{ .persistence.subPath | quote }}
              {{- end }}
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            {{- if .persistence.existingClaim }}
            claimName: {{ .persistence.existingClaim | quote }}
            {{- else }}
            claimName: '{{ $fullName }}-jms-koko-data'
            {{- end }}
          name: "jms-koko-data"
      {{- with .volumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
