{{- if .Values.koko.enabled }}
{{- with .Values.koko }}
{{- $fullName := include "jumpserver.fullname" $ }}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-jms-koko"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  annotations:
    {{- toYaml .service.annotations | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
    - port: {{ .service.ssh.port }}
      targetPort: ssh
      {{- if eq .service.type "NodePort" }}
      nodePort: {{ .service.ssh.port }}
      {{- end }}
      protocol: TCP
      name: ssh
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
{{- end }}
