{{- with .Values.core }}
{{- $fullName := include "jumpserver.fullname" $ }}
{{- $containerName := "jms-init-db" }}
{{- $registryName := $.Values.global.imageRegistry | default .image.registry }}
{{- $imageOwner :=  $.Values.global.imageOwner | default "jumpserver" }}
{{- $imageName := $.Values.xpack.enabled | ternary "core-ee" "core-ce" }}
{{- $imageTag := "v3.10.1" }}
{{- $imageWithTag := printf "%s/%s/%s:%s" $registryName $imageOwner $imageName $imageTag | quote }}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $fullName }}-{{ $containerName }}"
  labels:
    app.jumpserver.org/name: {{ $containerName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.global.imagePullSecrets }}
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ $imageWithTag }}
          imagePullPolicy: {{ .image.pullPolicy | quote }}
          command:
            - /bin/bash
            - "-c"
            - ./jms upgrade_db
          env:
            - name: SECRET_KEY
              value: {{ required "A valid secretKey is required!" .config.secretKey | quote }}
            - name: BOOTSTRAP_TOKEN
              value: {{ required "A valid bootstrapToken is required!" .config.bootstrapToken | quote }}
            - name: DB_ENGINE
              value: "{{ include "jumpserver.database.engine" $ }}"
            - name: DB_HOST
              value: {{ include "jumpserver.database.host" $ | quote }}
            - name: DB_PORT
              value: {{ include "jumpserver.database.port" $ | quote }}
            - name: DB_USER
              value: {{ include "jumpserver.database.user" $ | quote }}
            - name: DB_PASSWORD
              value: {{ include "jumpserver.database.password" $ | quote }}
            - name: DB_NAME
              value: {{ include "jumpserver.database.database" $ | quote }}
            {{- if include "jumpserver.sentinel.hosts" $ }}
            - name: REDIS_SENTINEL_HOSTS
              value: {{ include "jumpserver.sentinel.hosts" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.sentinel.password" $ }}
            - name: REDIS_SENTINEL_PASSWORD
              value: {{ include "jumpserver.sentinel.password" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.sentinel.socketTimeout" $ }}
            - name: REDIS_SENTINEL_SOCKET_TIMEOUT
              value: {{ include "jumpserver.sentinel.socketTimeout" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.host" $ }}
            - name: REDIS_HOST
              value: {{ include "jumpserver.redis.host" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.port" $ }}
            - name: REDIS_PORT
              value: {{ include "jumpserver.redis.port" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.password" $ }}
            - name: REDIS_PASSWORD
              value: {{ include "jumpserver.redis.password" $ | quote }}
            {{- end }}
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      restartPolicy: Never
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
