apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "update-jenkins-k8s-job.fullname" . }}
  labels:
    {{- include "update-jenkins-k8s-job.labels" . | nindent 4 }}
spec:
  strategy:
    # type: Recreate  # 关键配置：先删除旧 Pod，再创建新 Pod
    type: RollingUpdate  # 关键配置：先删除旧 Pod，再创建新 Pod
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}  
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "update-jenkins-k8s-job.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "manual restart at 2025-03-06 13:24:46"
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "update-jenkins-k8s-job.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "update-jenkins-k8s-job.serviceAccountName" . }}
        #serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
