apiVersion: v1
kind: Service
metadata:
  name: {{ include "update-jenkins-k8s-job.fullname" . }}
  labels:
    {{- include "update-jenkins-k8s-job.labels" . | nindent 4 }}
    {{- if .Values.prometheusDiscoveryEnabled }}
    micrometer-prometheus-discovery: "true"
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    app: {{ include "update-jenkins-k8s-job.name" . }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }} 

spec:
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}

  selector:
    {{- include "update-jenkins-k8s-job.selectorLabels" . | nindent 4 }}
