{{- with .Values.controller -}}
{{- if and .enabled -}}
{{- $clusterRole := "controller" -}}
{{- $image := printf "%s:%s" $.Values.image.repository $.Values.image.tag }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rocketmq.controller.fullname" $ | quote }}
  labels:
    {{- include "rocketmq.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: {{ .minReadySeconds | default 20 }}
  replicas: {{ .replicaCount }}
  podManagementPolicy: {{ .podManagementPolicy | default "Parallel" }}
  {{- with .updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rocketmq.selectorLabels" $ | nindent 6 }}
      component: {{ $clusterRole }}
  serviceName: {{ include "rocketmq.controller.fullname" $ | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        {{- with .podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "rocketmq.selectorLabels" $ | nindent 8 }}
        component: {{ $clusterRole }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .affinityOverride }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "rocketmq.selectorLabels" $ | nindent 18 }}
                  component: nameserver
              topologyKey: kubernetes.io/hostname
      {{- else if .affinityOverride }}
      affinity:
        {{- toYaml .affinityOverride | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: nameserver
        image: {{ $image | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | default "IfNotPresent" }}
        command:
          - sh
          - /mq-server-start.sh
        env:
        - name: ROCKETMQ_PROCESS_ROLE
          value: {{ $clusterRole }}
        - name: CONTROLLER_CONF_FILE
          value: /etc/rocketmq/controller.conf
        {{- if .jvm }}
        {{- with .jvm.maxHeapSize }}
        - name: ROCKETMQ_JAVA_OPTIONS_HEAP
          value: {{ printf "-Xms%s -Xmx%s" . . | quote }}
        {{- end }}
        {{- with .jvm.javaOptsOverride }}
        - name: ROCKETMQ_JAVA_OPTIONS_OVERRIDE
          value: {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 9878
          name: main
          protocol: TCP
        resources:
          {{- toYaml .resources | nindent 10 }}
        {{- with .readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5; ./mqshutdown controller"]
        volumeMounts:
        - mountPath: /mq-server-start.sh
          name: mq-server-start-sh
          subPath: mq-server-start.sh
        - mountPath: /etc/rocketmq/base-cm
          name: base-cm
        - mountPath: /home/rocketmq/controller-data
          name: data
          subPath: controller-data
        - mountPath: /home/rocketmq/logs
          name: data
          subPath: logs
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 15 }}
      volumes:
      - configMap:
          items:
          - key: mq-server-start.sh
            path: mq-server-start.sh
          name: {{ include "rocketmq.configmap.fullname" $ }}
          defaultMode: 0755
        name: mq-server-start-sh
      - configMap:
          name: {{ include "rocketmq.configmap.fullname" $ }}
        name: base-cm
  {{- if not .persistence.enabled }}
      - name: data
        emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- range .persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        {{- with .persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .persistence.size | quote }}
  {{- end }}
{{- end }}
{{- end }}