apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-dict-pvc
  namespace: online-users
  annotations:
    "helm.sh/resource-policy": "keep"  # 保留 PVC
spec:
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2

