---
domains:
  - g04backend.com
  - g04cfzone.com
  - g04gciweb.com
  - g04goproxy.com
  - g04uat.com
  - g09cfzone.com
  - g09game.com
  - g09uat.com
  - g13cfzone.com
  - g13game.com
  - g13uat.com
  # - intlivevideo.com
  - video-g16.com
  - prodg16.com
  - g04video-prod.com
  - g13video-prod.com
  - g20-uat.com
  - g23-uat.com
  - g29-uat.com
  - g29-prod.com
  - g22-uat.com
  - g22-prod.com
  - g22cfzone.com
  - game-moni.com
  - g16cfzone.com
  - g13gli.com
  - uatg16.com
  - g21green-prd.com
  - g12video-prod.com
  - g20-prod.com
  - myshow22.live
  - cfedge.net
  - solidleisure.net
  - g04gli.com
  - g16gli.com
  - g31gli.com
  - g31uat.com
  - g31prod.com
  - g31cfzone.com
  - g23-prod.com
  - g18-video.com
  - g20-video.com
  # g101-uat
  - g101-uat.com
  - g101-gli.com
  - g101-prod.com
  # g32
  - g32-gli.com
  - g32-uat.com
  - g32-prod.com
  - g32cfzone.com
  - g35-uat.com
  - g35-prod.com
  # g33-prod game domain
  - siteagent-client.com
  - dragontiger-game.com
  - speedbaccarat-game.com
  - classicbaccarat-game.com
  - roulettegame-frontend.com
  - sicbo-game.com
  - hyaknquaj.com
  - rhcfnrys.com
  - enesdsdb.com
  - tigshpmh.com
  - ghioggwq.com
  - g34-gli.com
  # g39
  - g39-gli.com
  - g39-uat.com
  - g34-prod.com