apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xxl-job-admin.fullname" . }}-config
  labels:
    {{- include "xxl-job-admin.labels" . | nindent 4 }}
data:
  application.yaml: |
{{ toYaml .Values.properties | indent 4 }}
{{- if .Values.skywalking.enabled }}
  init_skywalking.sh: |
{{ tpl .Values.skywalking.initScript . | indent 4 }}
{{- end }}
{{- if .Values.initDB.enabled }}
  init.sql: |
{{ tpl .Values.initDB.script . | indent 4 }}
{{- end }}