apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xxl-job-admin.fullname" . }}
  labels:
    {{- include "xxl-job-admin.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $varName, $varValue := .Values.mysql }}
  MYSQL_{{ $varName | upper }}: {{ required (printf "mysql.%s is required" $varName) $varValue | toString | b64enc | quote }}
  {{- end }}