{{- if .Values.lion.enabled }}
{{- with .Values.lion }}
{{- $fullName := include "jumpserver.fullname" $ }}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-jms-lion"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  annotations:
    {{- toYaml .service.annotations | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
{{- end }}
