apiVersion: v1
kind: Secret
metadata:
  name: g32-prod-deployment-https-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab-devops.slleisure.com/argocd/g32-prod-deployment.git
  password: 9yiLc8JU5AUJiiuzuYUU
  username: argo_read_repository
  insecure: "false" # Ignore validity of server's TLS certificate. Defaults to "false"
  forceHttpBasicAuth: "false" # Skip auth method negotiation and force usage of HTTP basic auth. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"

