apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: g32-istio-ingressgateway-inner
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: g32-istio-ingressgateway-inner
  namespaceSelector:
    any: true
  endpoints:
    - port: envoy-metrics
      path: /stats/prometheus
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: g32-istio-ingressgateway-extra
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: g32-istio-ingressgateway-extra
  namespaceSelector:
    any: true
  endpoints:
    - port: envoy-metrics
      path: /stats/prometheus
      interval: 15s