---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # name: istio-servicemonitor
  name: istio-ingressgateway
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /stats/prometheus 
      interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # name: istio-internal-servicemonitor
  name: istio-ingressgateway-internal
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      # app: istio-ingressgateway-internal
      app: istio-ingressgateway-internal
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /stats/prometheus   
      interval: 30s


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    any: true
  endpoints:
    - port: http-monitoring
      path: /metrics  
      interval: 30s