apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: g101-backup-log
  namespace: g101-tidb
spec:
  backupMode: log
  br:
    cluster: g101-prod
    clusterNamespace: g101-tidb
    sendCredToTikv: true
  s3:
    provider: aws
    secretName: s3-secret
    region: ap-east-1
    bucket: g101-prod
    prefix: g101_tidb_log
