{{- if .Values.proxy.enabled -}}
{{- with .Values.proxy.service -}}
{{- $clusterRole := "proxy" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.proxy.fullname" $ }}
  labels:
    {{- include "rocketmq.labels" $ | nindent 4 }}
    component: {{ $clusterRole }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 8080
    name: main
    protocol: TCP
    targetPort: 8080
    {{- if and (eq .type "NodePort") .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
  - port: 8081
    name: grpc
    protocol: TCP
    targetPort: 8081
    {{- if and (eq .type "NodePort") .nodePortGrpc }}
    nodePort: {{ .nodePortGrpc }}
    {{- end }}
  {{- with .additionalPorts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    {{- include "rocketmq.selectorLabels" $ | nindent 4 }}
    component: {{ $clusterRole }}
  {{- with .type }}
  type: {{ . | quote }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .type) .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP | quote }}
  {{- end }}
  {{- with .loadBalancerClass }}
  loadBalancerClass: {{ . | quote }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . | quote }}
  {{- end }}
  {{- with .sessionAffinity }}
  sessionAffinity: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}