apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-extra
  namespace: devops
spec:
  ports:
    - port: 9200     
      targetPort: 9200
      protocol: TCP     
  clusterIP: None       
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch-extra
  namespace: devops
subsets:
  - addresses:
      - ip: 10.160.0.39
      - ip: 10.160.0.40
      - ip: 10.160.0.41
      - ip: 10.160.0.42
      - ip: 10.160.0.43
    ports:
      - port: 9200
        protocol: TCP