{{- if .Values.web.enabled }}
{{- with .Values.web }}
{{- $fullName := include "jumpserver.fullname" $ }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ $fullName }}-jms-web"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
data:
{{- $path := printf "%s/%s/%s" "configs" "jms-web" "default.conf" -}}
{{- tpl (( $.Files.Glob $path ).AsConfig) $ | nindent 2 }}
{{- end }}
{{- end }}
