{{- if .Values.magnus.enabled }}
{{- with .Values.magnus }}
{{- $fullName := include "jumpserver.fullname" $ }}
{{- $containerName := "jms-magnus" }}
{{- $registryName := $.Values.global.imageRegistry | default .image.registry }}
{{- $imageOwner :=  $.Values.global.imageOwner | default "jumpserver" }}
{{- $mysqlPort := printf "%s" (include "jumpserver.magnus.mysql.port" $) }}
{{- $mariadbPort := printf "%s" (include "jumpserver.magnus.mariadb.port" $) }}
{{- $redisPort := printf "%s" (include "jumpserver.magnus.redis.port" $) }}
{{- $postgresqlPort := printf "%s" (include "jumpserver.magnus.postgresql.port" $) }}
{{- $oraclePorts := printf "%s" (include "jumpserver.magnus.oracle.ports" $) }}
{{- $oraclePortStart := printf "%s" (include "jumpserver.magnus.oracle.port.start" $) | int }}
{{- $oraclePortEnd := printf "%s" (include "jumpserver.magnus.oracle.port.end" $) | int }}
{{- $imageName := "magnus" }}
{{- $imageTag := "v3.10.1" }}
{{- $imageWithTag := printf "%s/%s/%s:%s" $registryName $imageOwner $imageName $imageTag | quote }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-{{ $containerName }}"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.global.imagePullSecrets }}
      {{- end }}
      serviceAccountName: {{ template "jumpserver.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ $imageWithTag }}
          imagePullPolicy: {{ .image.pullPolicy | quote }}
          env:
            - name: CORE_HOST
              value: "http://{{ $fullName }}-jms-core:{{ $.Values.core.service.web.port }}"
            - name: BOOTSTRAP_TOKEN
              value: {{ $.Values.core.config.bootstrapToken | quote }}
            - name: LOG_LEVEL
              value: {{ .config.log.level | quote }}
            - name: SHARE_ROOM_TYPE
              value: "redis"
            {{- if include "jumpserver.sentinel.hosts" $ }}
            - name: REDIS_SENTINEL_HOSTS
              value: {{ include "jumpserver.sentinel.hosts" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.sentinel.password" $ }}
            - name: REDIS_SENTINEL_PASSWORD
              value: {{ include "jumpserver.sentinel.password" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.sentinel.socketTimeout" $ }}
            - name: REDIS_SENTINEL_SOCKET_TIMEOUT
              value: {{ include "jumpserver.sentinel.socketTimeout" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.host" $ }}
            - name: REDIS_HOST
              value: {{ include "jumpserver.redis.host" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.port" $ }}
            - name: REDIS_PORT
              value: {{ include "jumpserver.redis.port" $ | quote }}
            {{- end }}
            {{- if include "jumpserver.redis.password" $ }}
            - name: REDIS_PASSWORD
              value: {{ include "jumpserver.redis.password" $ | quote }}
            {{- end }}
            - name: MAGNUS_MYSQL_PORT
              value: {{ $mysqlPort | quote }}
            - name: MAGNUS_MARIADB_PORT
              value: {{ $mariadbPort | quote }}
            - name: MAGNUS_REDIS_PORT
              value: {{ $redisPort | quote }}
            - name: MAGNUS_POSTGRESQL_PORT
              value: {{ $postgresqlPort | quote }}
            - name: MAGNUS_ORACLE_PORTS
              value: {{ $oraclePorts | quote }}
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: mysql
              containerPort: {{ $mysqlPort }}
              protocol: TCP
            - name: mariadb
              containerPort: {{ $mariadbPort }}
              protocol: TCP
            - name: redis
              containerPort: {{ $redisPort }}
              protocol: TCP
            - name: postgresql
              containerPort: {{ $postgresqlPort }}
              protocol: TCP
            {{- if $.Values.xpack.enabled }}
            {{- range $port := untilStep $oraclePortStart $oraclePortEnd 1 }}
            - name: oracle-{{ $port }}
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/magnus/data"
              name: "jms-magnus-data"
              {{- if .persistence.subPath }}
              subPath: {{ .persistence.subPath | quote }}
              {{- end }}
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            {{- if .persistence.existingClaim }}
            claimName: {{ .persistence.existingClaim | quote }}
            {{- else }}
            claimName: '{{ $fullName }}-jms-magnus-data'
            {{- end }}
          name: "jms-magnus-data"
      {{- with .volumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
