{{- if .Values.magnus.enabled }}
{{- with .Values.magnus }}
{{- $fullName := include "jumpserver.fullname" $ }}
{{- $mysqlPort := printf "%s" (include "jumpserver.magnus.mysql.port" $) }}
{{- $mariadbPort := printf "%s" (include "jumpserver.magnus.mariadb.port" $) }}
{{- $redisPort := printf "%s" (include "jumpserver.magnus.redis.port" $) }}
{{- $postgresqlPort := printf "%s" (include "jumpserver.magnus.postgresql.port" $) }}
{{- $oraclePortStart := printf "%s" (include "jumpserver.magnus.oracle.port.start" $) | int }}
{{- $oraclePortEnd := printf "%s" (include "jumpserver.magnus.oracle.port.end" $) | int}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-jm-magnus"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  annotations:
    {{- toYaml .service.annotations | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.mysql.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: {{ .service.mariadb.port }}
      targetPort: mariadb
      protocol: TCP
      name: mariadb
    - port: {{ .service.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- if $.Values.xpack.enabled }}
    - port: {{ .service.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
    {{- if $.Values.xpack.enabled }}
    {{- range $port := untilStep $oraclePortStart $oraclePortEnd 1 }}
    - port: {{ $port }}
      {{- if eq $.Values.magnus.service.type "NodePort" }}
      nodePort: {{ $port }}
      {{- end }}
      targetPort: oracle-{{ $port }}
      protocol: TCP
      name: oracle-{{ $port }}
    {{- end }}
    {{- end }}
    {{- end }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
{{- end }}
