# # collect interval
# interval = 15

[[instances]]
# kubelete metrics & cadvisor
type = "kubelet"
url = "https://127.0.0.1:10250/metrics/cadvisor"
url_label_key = "instance"
url_label_value = "{{.Host}}"
bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
ignore_label_keys = ["id","name", "container_label*"]
# 只采集那些label key, 建议保持为空，采集所有的label。 优先级高于ignore_label_keys。
# choose_label_keys = ["*"]
use_tls = true
insecure_skip_verify = true