---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: g32-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: g32 Monte Prod
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://10.199.0.31
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
